### ISSUE TITLE
The given webpack config cause errors ?

### ISSUE THREAD

**Issue by daiyanze** [gadyonysh/semantic-ui-react-less-loader#3]
#### The default Webpack config is
```js
{
      test: /\.jsx?$/,
      loader: 'babel!semantic-ui-react-less-loader',
      include: [/node_modules[\/\\]semantic-ui-react/]
}
```
Error1:

![2017-07-27 18 02 35](https://user-images.githubusercontent.com/14920529/28662706-02a8a792-72f6-11e7-8cf5-758a66cb16ef.png)

#### After I added '-loader' after babel
```
...
loader: 'babel-loader!semantic-ui-react-less-loader',
...
```

Error2:
![2017-07-27 18 05 45](https://user-images.githubusercontent.com/14920529/28662783-4e40236a-72f6-11e7-9e7c-cbf8917355ae.png)
![2017-07-27 18 05 58](https://user-images.githubusercontent.com/14920529/28662786-50358d7c-72f6-11e7-99db-e7a2479908a1.png)

#### It seems that `babel-loader` and `semantic-ui-react-less-loader` need to be used separately. So I made the Webpack config into
```js
{
     test: /\.jsx?$/,
     loader: 'babel-loader',
     include: [/node_modules[\/\\]semantic-ui-react/]
},
{
     test: /\.less$/,
     loader: 'semantic-ui-react-less-loader',
     include: [/node_modules[\/\\]semantic-ui-react/]
}
```
#### Now it works properly with Semantic UI React

**Comment by daiyanze** [comment]
This problem cost me whole hour. Hope my solution may help others.

**Comment by gadyonysh** [comment]
Hello, @daiyanze 

About error 1: It looks like you use webpack >= v.2 and this case is described in [migration guide](https://webpack.js.org/guides/migrating/#automatic-loader-module-name-extension-removed).

About error 2: After you had fixed error 1, semantic-ui-react-less-loader just did its job: it added corresponding ".less" files for sui-react components. To process sui-less files you need to use [semantic-ui-less-module-loader](https://github.com/gadyonysh/semantic-ui-less-module-loader)

Also there's a problem in provided config section:
```js
{
     test: /\.jsx?$/,
     loader: 'babel-loader',
     include: [/node_modules[\/\\]semantic-ui-react/]
},
{
     test: /\.less$/,
     loader: 'semantic-ui-react-less-loader',
     include: [/node_modules[\/\\]semantic-ui-react/]
}
```
You've tried to use semantic-ui-react-less-loader for ".less" files (test: /\.less$/), but there is no ".less" files  in /node_modules/semantic-ui-react/ (include: [/node_modules[\/\\]semantic-ui-react/]).

You can look at my config example for webpack v.2 in [this comment](https://github.com/gadyonysh/semantic-ui-react-less-loader/issues/2#issuecomment-301733468)

**Comment by daiyanze** [comment]
I think you made the point, we don't need an extra `less-loader` for `semantic-ui-react` since there is no less loader in source files.
Thank you for your help. 

Anyway, our team is working on a prototype, we couldn't spare much time on configurations.
So we decide to use Ant Design instead.
